### ISSUE TITLE
[TC] Items not showing after commit [432]

### ISSUE THREAD

**Issue by duergar85** [Shadez/wowarmory#106] opened 2010-12-30 17:57 UTC
After your commit [432] Variable Checks, visualization of items is broken on TrinityCore. After some tests I noticed that this is the problem:
-            -  $this->entry = $this->tc_data['itemEntry'];
-            +  $this->entry = (isset($this->tc_data['itemEntry'])) ? $this->tc_data['itemEntry'] : (isset($this->tc_data['item_template'])) ? $this->tc_data['item_template'] : 0;

on line 106 of includes/classes/class.item.php.
As soon as I came back to the first one, everything works normal again. I also tried to rewrite that if with a "normal" if and it wouldn't work too.

Another thing I noticed is that the Max Durability of every item is wrong or 0 in the tooltips. I tried to discover the error and all is normal in the PHP files. I suppose that the problem is in the XSL that generate the tooltip but I was not able to fix that, not even to understand HOW that generation work like.

Any help will be appreciated, thanks for the hard work on the Armory.

duergar85

**Comment by Shadez** [comment] 2010-12-30 20:25
> After your commit [432] Variable Checks, visualization of items is broken on TrinityCore.

Thank you, this was fixed in [436] commit. I've added this check for my internal tests and forgot to remove before commit changes.

> Another thing I noticed is that the Max Durability of every item is wrong or 0 in the tooltips.

This should be also fixed in prev. commits. Please, check it and report back if it wasn't fixed.

**Comment by Shadez** [comment] 2010-12-30 20:29
Correct me if I'm wrong - you mean that MaxDurability data was broken after [432] changes? Or it was broke before it?
If after [432], then the reason of the problem is in incorrect item entry generation. If before, I need more researchs on this problem. 
Thank you.

**Comment by duergar85** [comment] 2010-12-30 20:36
MaxDurability was broken even before [432]. I was just checking something but the file .cache generated by item-tooltip.php is perfect and so is the page showing only the item (when clicking on it from the Character Sheet). The only wrong part is the Tooltip in the Character Sheet. I tried with an item with 35 / 35 of durability and it keep showing 35 / 25 in the tooltip even if the .cache report a correct <durability current="35" max="35"/>

Edit: I'm gonna check with the new commits and tell you if it's still bugged.

**Comment by Shadez** [comment] 2010-12-30 20:50
That's very odd. Try to drop cache (or temporary disable it) and re-build page. Also, you can try to open http://armory_url/item-toolip.xml?i=item_entry&r=realm_name&cn=character_name&skipCache=true and check it there.

**Comment by duergar85** [comment] 2010-12-30 20:55
Just tried that link and it's still bugged, showing 
"Durability: 35 / 25"
Everything else is correct.

I'm still cloning all the code, I will need some more time to check with the new commits.

**Comment by duergar85** [comment] 2010-12-30 21:18
Ok, with the fixes of [437] it's all working now.
Thanks again for the fixes! :)

duergar85

**Comment by Shadez** [comment] 2010-12-30 21:29
Thanks for reports!

**Closed as completed** 2010-12-31 05:18 UTC
