### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by stampis** [Shadez/wowarmory#34] opened 2010-06-25 18:52 UTC
1. Random enchants does not show on items (tested with some low green pants / gloves / etc..)
2. Characters are naked on the 3d-viewer

Other than that is almost perfect :-)
Some extra info from debug-file

<strong>ERROR</strong> [25-06-2010 20:46:15]: Characters::getCharacterEnchant : wrong item slot query: Array<br />
<strong>ERROR</strong> [25-06-2010 20:46:15]: Characters::GetCharacterItemInfo : unable to get item_id for player 1 (Testo); slotid is mainhand<br />

(The second one that report unable to get item_id for mainhand weapon is cuz there is no mainhand weapon on that character, shouldent it "see" that? or check if there is a weapon equiped or not?)

**Comment by Shadez** [comment] 2010-06-25 23:05
> Characters are naked on the 3d-viewer

I can't reproduce this bug. Look at your Apache server log for some 404 errors.

> Random enchants does not show on items (tested with some low green pants / gloves / etc..)

It's works for me... Is your armory db up-to-date?

**Comment by stampis** [comment] 2010-06-26 00:22
I updated to the latest rev267 but still have the same issues... Naked characters (or not displayed at all in some cases) and no stats are shown on items that have <random> stats (like Boots of the Boar should show stamina but dosent)..

The only errors in Apache right now is;

[Sat Jun 26 02:14:14 2010] [error] File does not exist: D:/www/wow-icons/_images/21x21/0.png, referer: http://127.0.0.1/character-sheet.xml?r=Test&cn=Testu

[Sat Jun 26 02:14:14 2010] [error] File does not exist: D:/www/models/item/objectcomponents/weapon/.m2

[Sat Jun 26 02:14:14 2010] [error] File does not exist: D:/www/models/item/objectcomponents/weapon/.jpg
[Sat Jun 26 02:14:14 2010] [error] File does not exist: D:/www/models/item/objectcomponents/weapon/.png

The armory db seems up-to-date yes.. The table's that hold info about random enchantments are there and contain the correct info...

::EDIT::
After rev267 i dont get anymore "errors" about Characters::getCharacterEnchant etc in the 'tmp.dbg' file from the armory...

::EDIT 2::
I also dont see durability on characters items in armory (maybe i shouldent? so not a bug really..)

**Comment by Shadez** [comment] 2010-06-26 01:45
> no stats are shown on items that have stats (like Boots of the Boar should show stamina but dosent)..

Sorry, I've just checked this feature and it's really broken. It will be fixed as soon as i'll find bug reason.

And I have no idea about 3D Viewer right now, but I'll look more deep into this issue.

Thank you for reporting.

**Comment by stampis** [comment] 2010-06-26 16:55
On rev268 nothing works anymore...
When i try to load characters or items the page is totaly white..
There is no error in apache log (on debug level) and nothing wrong in the tmp.dbg file from the armory with debug enable / loglevel 2...

Dont get me wrong... even without the temp enchantments and 3d viewer this is the best armory i've seen :-) just trying to help sort out these issues best i can...

**Comment by stampis** [comment] 2010-07-03 05:28
Confirmed...
Still naked characters on rev281..

Also random enchantments only work for old-world items and not WoTLK items?

**Comment by Shadez** [comment] 2010-07-07 03:35
No, it can't help. AFAIK, all your models loads properly and I have no idea why your chars are naked.

**Comment by stampis** [comment] 2010-07-07 03:39
@Shadez
have you tested under Windows or do you only test under Unix?
The only 'common' thing people with this issue have seems to be that they;
1) use windows
2) use wamp or xampp

**Comment by Shadez** [comment] 2010-07-07 03:47
I have tests only on Windows (Win7). And I can't guarantee that Wamp/Xampp are good servers for Armory.

**Comment by stampis** [comment] 2010-07-07 03:51
What version(s) of Php / apache / modules, etc :S

I got this issue and i have the following;
Apache/2.2.14 (Win32) DAV/2 mod_ssl/2.2.14
OpenSSL/0.9.8l
PHP/5.3.1

**Comment by Shadez** [comment] 2010-07-07 12:04
> What version(s) of Php / apache / modules, etc :S

Apache/2.2.4 (Win32) mod_ssl/2.2.4 OpenSSL/0.9.8d PHP/5.2.4

> Shadez, how it's possible that before very much updates it worked?

There's only one change to model viewer after 228 rev. and it's can't affect on proper 3D work.

I don't know what's wrong with your viewer, but it's work for me if there're no Arena 8 Season items on character equipped. If you want, I can provide link to my local web-server and you can look at it yourself. PM me for info.

**Comment by stampis** [comment] 2010-07-07 20:21
I have tested with both starter gear (ie; very low level items)
and higher (but not any Arena / Tier items)..
Still same issue 'Naked character'..

Any php settings / apache settings that could be the problem :-/?
or do you use 'vanilla' settings?

**Comment by gyullo** [comment] 2010-08-06 09:56
I have problems with gems, enchants work just fine

**Closed as completed** 2010-09-26 02:52 UTC
